version: "3.11.2"

services:
  web:
    build: .
    command: gunicorn authenticated_things_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=rock
      - POSTGRES_USER=rock
      - POSTGRES_PASSWORD=rock